name: dp-solver-env
channels:
  - conda-forge
  - dglteam
  - defaults
dependencies:
  - _pytorch_select=0.1
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - cycler=0.10.0
  - decorator=4.4.2
  - dgl=1.1.0
  - freetype=2.9.1
  - intel-openmp=2019.4
  - kiwisolver=1.1.0
  - libcxx
  - libcxxabi
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran
  - libpng=1.6.37
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.2
  - networkx=2.4
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1g
  - pip=20.0.2
  - pybind11=2.4.3
  - pycparser=2.20
  - pyparsing=2.4.6
  - python=3.7.7
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.4.0
  - readline=8.0
  - scipy=1.4.1
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - tornado=6.0.4
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11

